services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./back
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - ./back:/usr/src/app
    env_file:
    - .env
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  test:
    build:
      dockerfile: Dockerfile
      context: ./back
      target: development
    volumes:
      - ./back:/usr/src/app
    env_file:
    - .env
    command: npm run test

volumes:
  redis:
    driver: local
